name: Auto Sync

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Fork
        uses: actions/checkout@v3
        with:
          ref: master
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Fetch Upstream Master
        run: |
          git remote add upstream https://github.com/MeteorDevelopment/meteor-client.git
          git fetch upstream master
          git checkout master

      - name: Check Fork Status
        id: check
        run: |
          UPSTREAM=$(git rev-parse upstream/master)
          FORK=$(git rev-parse origin/master)  # Compare the master branches explicitly

          if [ "$UPSTREAM" != "$FORK" ]; then
            echo "Fork is behind upstream."
            echo "::set-output name=behind::true"
          else
            echo "Fork is up to date."
            echo "::set-output name=behind::false"
          fi

      - name: Merge and Push
        if: steps.check.outputs.behind == 'true'
        run: |
          git merge upstream/master
          git push origin master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
